API_KEY = 'RGAPI-2433ebf5-63ad-4c56-be42-19013c5e7c2e'
REGION = 'euw1'

LIST_FIELDS = ['summonerName',
               'summonerLevel',
               'win',
               'kills',
               'deaths',
               'assists',
               'bountyLevel',
               'completeSupportQuestInTime',
               'controlWardTimeCoverageInRiverOrEnemyHalf',
               'bountyOro',
               'controlWardsPlaced',
               'damagePerMinute',
               'damageTakenOnTeamPercentage',
               'kda',
               'laneMinionsFirst10Minutes',
               'legendaryCount',
               'maxCsAdvantageOnLaneOpponent',
               'maxLevelLeadLaneOpponent',
               'multikills',
               'skillshotsHit',
               'soloKills',
               'teamDamagePercentage',
               'visionScorePerMinute',
               'saveAllyFromDeath',
               'skillshotsDodged',
               'wardTakedowns',
               'champLevel',
               'earlyLaningPhaseOroExpAdvantage',
               'effectiveHealAndShielding',
               'gameLength',
               'OroPerMinute',
               'hadAfkTeammate',
               'hadOpenNexus',
               'stealthWardsPlaced',
               'OroEarned',
               'OroSpent',
               'detectorWardsPlaced',
               'jungleCsBefore10Minutes',
               'killParticipation',
               'timeCCingOthers',
               'killingSprees',
               'challenge_outnumberedKills',
               'doubleKills',
               'pentaKills',
               'quadraKills',
               'tripleKills',
               'gameEndedInSurrender',
               'largestKillingSpree',
               'longestTimeSpentLiving',
               'teamId',
               'teamPosition',
               'timePlayed',
               'totalDamageDealt',
               'totalDamageTaken',
               'totalHeal',
               'totalMinionsKilled',
               'totalTimeCCDealt',
               'totalTimeSpentDead',
               'visionScore',
               'challenge_junglerKillsEarlyJungle']

LOL_DIVISIONS = {'Hierro IV': 0, 'Hierro III': 1, 'Hierro II': 2, 'Hierro I': 3 , 'Bronce IV': 4, 'Bronce III': 5,
                 'Bronce II': 6, 'Bronce I': 7, 'Plata IV': 8, 'Plata III': 9, 'Plata II': 10, 'Plata I': 11,
                 'Oro IV': 12, 'Oro III': 13, 'Oro II': 14, 'Oro I': 15, 'Platino IV': 16, 'Platino III': 17,
                 'Platino II': 18, 'Platino I': 19, 'Diamante IV': 20, 'Diamante III': 21, 'Diamante II': 22,
                 'Diamante I': 23, 'Master': 24, 'GrandMaster': 25, 'Challenger': 26}
